query getLeaguesByUserID (
  $userId: ID!
) {
  allLeagues(filter: {
    members_every: {
      id: $userId
    }
  }) {
    id,
    leagueName
    contests {
      id
      start
      end
    }
  }
}