query getStats {
  allGolfStatses(orderBy: thisWeek_ASC) {
    id
    name
    thisWeek
  }
}

mutation updateOrCreateEntry(
  $id: ID!
  $entryName: String
  $ownerId: ID!
  $contestId: ID!
  $picks: [String!]
) {
  updateOrCreateEntry(
    update: {
      id: $id
      entryName: $entryName
      ownerId: $ownerId
      contestId: $contestId
      picks: $picks
    }
    create: {
      ownerId: $ownerId
      entryName: $entryName
      contestId: $contestId
      picks: $picks
      rank: 1
    }
  ) {
    id
  }
}

mutation updateContest(
 	$contestId: ID!
  $dummy: String
){
  updateContest(
    id: $contestId
    dummy: $dummy
  ) {
    id
  }
}