fragment LeagueData on League {
  id
  leagueName
  members {
    id
    firstName
    lastName
    email
    wins: userEntries(filter: {
      rank: 1
      contest: {
        end_lte: $now
        league: {
          id: "cjwwlfh6905xd0186f2mlh8a0"
        }
      }
    }) {
      id
    }
  },
  contests {
    id
    contestName
    limitEntries
    numberOfEntries
    ownedEntries: entries(filter: {owner: {
      id: $userId
    }}) {
      id
    }
    entries(orderBy: rank_ASC) {
        id
        createdAt
        picks
        entryName
        owner {
          id
          firstName
          lastName
          email
        }
        rank
      }
    scoringFormats
    sports
    events {
      id
      sport
      participants
      leaderboard
      name
      start
      end
    }
    start
    end
  }
}

query getLeague($leagueId: ID!, $userId: ID!, $now: DateTime) {
  League(id: $leagueId) {
    ...LeagueData
  }
}

subscription LeagueUpdateSubscription(
  $id: ID!, $userId: ID!, $now: DateTime
) {
  League(filter: {
    mutation_in: [UPDATED]
    node: {
      id: $id
    }
  }) {
    node {
      ...LeagueData
    }
  }
}

subscription ContestUpdateSubscription(
  $leagueId: ID!, $userId: ID!, $now: DateTime
) {
  Contest(filter: {
    mutation_in: [UPDATED]
    node: {
      league: {
        id: $leagueId
      }
    }
  }) {
    node {
      league {
        ...LeagueData
      }
    }
  }
}